### ISSUE TITLE
If integer value is zero with notempty tag, validator is expected true.

### ISSUE THREAD

**Issue by odg0318** [goburrow/validator#1]
Now, with notempty , validator set to false if integer value is zero.
I know that the default value of integer is zero but zero is also a kind of lots of values.
It is reasonable to decide whether zero is or not using minmax.

What do you think of this issue?

**Comment by nqv** [comment]
Hi @odg0318, Sorry for slow response.
`notempty` respects zero value as specified in Golang [spec](https://golang.org/ref/spec#The_zero_value). Do you have a use case to use `notempty` with `int`? I meant if you allow zero value, you don't need `notempty` tag, do you?

On the other hand, if you just want to assure an `int` is present, I'd recommend using `*int`, e.g
```go
type S struct {
    MustInt *int `valid:"notempty"`
}
```

**Comment by odg0318** [comment]
It helps me so much. Thanks!
